using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SDQ
{
    class Program
    {
        static void Main(string[] args)
        {
            var src = @".\";
            if (args.Length > 0)
                src = args[1];
            var everything = Toolkit.DataAccessLayer.AllFiles(src);
            Console.WriteLine(everything.Aggregate("files:", (box, it) => $"{box}\n- {it}"));
            // TODO Get only files generated by SDQ test
            // TODO For each file, generate analysis file
            Console.ReadLine();
        }
    }
}
